I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 51, in script
    show screen hbox_screen
  File "renpy/common/000statements.rpy", line 501, in execute_show_screen
    renpy.show_screen(name, *args, **kwargs)
Exception: Screen hbox_screen is not known.


-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 51, in script
    show screen hbox_screen
  File "/home/gkiss/Misc/renpy-6.99.14.3-sdk/renpy/ast.py", line 1828, in execute
    self.call("execute")
  File "/home/gkiss/Misc/renpy-6.99.14.3-sdk/renpy/ast.py", line 1816, in call
    return renpy.statements.call(method, parsed, *args, **kwargs)
  File "/home/gkiss/Misc/renpy-6.99.14.3-sdk/renpy/statements.py", line 177, in call
    return method(parsed, *args, **kwargs)
  File "renpy/common/000statements.rpy", line 501, in execute_show_screen
    renpy.show_screen(name, *args, **kwargs)
  File "/home/gkiss/Misc/renpy-6.99.14.3-sdk/renpy/display/screen.py", line 1060, in show_screen
    raise Exception("Screen %s is not known.\n" % (name[0],))
Exception: Screen hbox_screen is not known.


Linux-4.13.0-38-generic-x86_64-with-debian-stretch-sid
Ren'Py 6.99.14.3.3347
RenpyTest 1.0
Thu Apr 12 07:18:32 2018
